Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-01, with the labels that each got.

#1 Add directory structure for the tool
  inference_perf/client/__init__.py
  inference_perf/client/request_processor.py
  inference_perf/client/response_processor.py
  inference_perf/config.py
  inference_perf/dataset/__init__.py
  inference_perf/dataset/preprocessor.py
  inference_perf/loadgen/__init__.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  inference_perf/reportgen/__init__.py
  inference_perf/reportgen/report_generator.py
  inference_perf/utils/__init__.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#3 Add Makefile and typecheck presubmit
  .github/workflows/format.yml
  .gitignore
  Makefile
  inference_perf/client/__init__.py
  inference_perf/client/request_processor.py
  inference_perf/client/response_processor.py
  inference_perf/config.py
  inference_perf/dataset/__init__.py
  inference_perf/dataset/preprocessor.py
  inference_perf/loadgen/__init__.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  inference_perf/reportgen/__init__.py
  inference_perf/reportgen/report_generator.py
  inference_perf/utils/__init__.py
  requirements.txt
  requirements/build.txt
  requirements/run.txt
Labels: size/L, lgtm, approved, cncf-cla: yes

#6 Fix Makefile Typo
  Makefile
Labels: lgtm, approved, size/XS, cncf-cla: yes

#4 Add design document to the repo
  docs/design.md
  docs/images/design.png
Labels: size/M, lgtm, approved, cncf-cla: yes
