Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-05, with the labels that each got.

#62 Lint and type check fixes
  inference_perf/datagen/base.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/main.py
  inference_perf/utils/custom_tokenizer.py
  pdm.lock
  pyproject.toml
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#64 Added Prometheus client to get model server metrics
  config.yml
  inference_perf/client/base.py
  inference_perf/client/mock_client.py
  inference_perf/client/vllm_client.py
  inference_perf/config.py
  inference_perf/main.py
  inference_perf/metrics/README.md
  inference_perf/metrics/__init__.py
  inference_perf/metrics/base.py
  inference_perf/metrics/mock_client.py
  inference_perf/metrics/prometheus_client.py
  inference_perf/reportgen/__init__.py
  inference_perf/reportgen/base.py
  pyproject.toml
Labels: lgtm, ok-to-test, approved, size/XL, cncf-cla: yes

#66 Add support for different input distributions with a synthetic dataset
  README.md
  examples/vllm/config-synthetic.yml
  inference_perf/client/vllm_client.py
  inference_perf/config.py
  inference_perf/datagen/__init__.py
  inference_perf/datagen/base.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/main.py
Labels: lgtm, approved, size/XL, cncf-cla: yes

#71 Automatically Populate Missing Fields in Config
  inference_perf/client/request_processor.py
  inference_perf/client/response_processor.py
  inference_perf/config.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#72 Generic model server client config
  .gitignore
  config.yml
  examples/vllm/config-synthetic.yml
  examples/vllm/config.yml
  inference_perf/client/modelserver/__init__.py
  inference_perf/client/modelserver/base.py
  inference_perf/client/modelserver/mock_client.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  inference_perf/metrics/base.py
  inference_perf/metrics/mock_client.py
  inference_perf/metrics/prometheus_client.py
  inference_perf/reportgen/base.py
  inference_perf/utils/custom_tokenizer.py
  pdm.lock
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#79 Add output distribution to synthetic data generator
  examples/vllm/config-synthetic.yml
  examples/vllm/vllm_server.ipynb
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/main.py
  inference_perf/prompts/completion.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#83 Add the option to ignore end of sequence
  config.yml
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/main.py
  inference_perf/prompts/base.py
  inference_perf/prompts/chat.py
  inference_perf/prompts/completion.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#41 Add GitHub Release Workflow and Changelog Configuration
  .github/changelog-config.json
  .github/workflows/release.yml
Labels: size/M, lgtm, approved, cncf-cla: yes

#90 Add issue templates for the repo
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M, lgtm, approved, cncf-cla: yes

#91 docs: Update link to Slack channel in README.md
  README.md
Labels: lgtm, approved, size/XS, cncf-cla: yes

#95 Multi-stage report generation for Prometheus Metrics
  config.yml
  inference_perf/client/metricsclient/base.py
  inference_perf/client/metricsclient/mock_client.py
  inference_perf/client/metricsclient/prometheus_client.py
  inference_perf/config.py
  inference_perf/datagen/random_datagen.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  inference_perf/reportgen/base.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#97 Add Docker build and push workflows for PRs and releases
  .github/workflows/docker-build.yml
  .github/workflows/release.yml
Labels: size/M, lgtm, approved, cncf-cla: yes

#101 Added throughput metrics to output report
  inference_perf/reportgen/base.py
Labels: lgtm, approved, size/XS, cncf-cla: yes

#102 Enable Docker Build Workflow on Push to Main Branch
  .github/workflows/docker-build.yml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#105 Fix Docker Tag Generation by Using env.QUAY_USERNAME in Workflow
  .github/workflows/docker-build.yml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#106 Update Quay.io Organization Name in Docker Build Workflow
  .github/workflows/docker-build.yml
Labels: lgtm, approved, size/XS, cncf-cla: yes
