Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-06, with the labels that each got.

#103 Add Support for Streaming Requests to Completions API
  config.yml
  examples/vllm/config-random.yml
  examples/vllm/config.yml
  inference_perf/apis/base.py
  inference_perf/apis/chat.py
  inference_perf/apis/completion.py
  inference_perf/client/modelserver/base.py
  inference_perf/client/modelserver/mock_client.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/datagen/base.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/datagen/random_datagen.py
  inference_perf/datagen/shared_prefix_datagen.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/main.py
  inference_perf/reportgen/base.py
  tests/apis/test_chat.py
  tests/apis/test_completion.py
  tests/test_config.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#99 Add multiprocess, multithreaded loadgen
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/client/requestdatacollector/__init__.py
  inference_perf/client/requestdatacollector/multiprocess.py
  inference_perf/config.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  inference_perf/reportgen/base.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#104 Update documentation to cover newer capabilities
  README.md
  docs/images/architecture.png
  examples/vllm/config-random.yml
  examples/vllm/config-synthetic.yml
  examples/vllm/vllm_server.ipynb
Labels: size/L, lgtm, approved, cncf-cla: yes

#112 Fix loadgen hang
  inference_perf/client/requestdatacollector/multiprocess.py
  inference_perf/loadgen/load_generator.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#115 Merge the latest fixes to the release branch
  inference_perf/client/requestdatacollector/multiprocess.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/loadgen/load_generator.py
Labels: size/M, approved, cncf-cla: yes

#118 Simplified local report storage
  .gitignore
  inference_perf/apis/chat.py
  inference_perf/apis/completion.py
  inference_perf/client/filestorage/__init__.py
  inference_perf/client/filestorage/local.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/main.py
  inference_perf/reportgen/base.py
  inference_perf/utils/report_file.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#120 Add support for api_key #116
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/main.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#128 fix: improve Docker build workflow with better secret handling and debugging
  .github/workflows/release.yml
Labels: size/M, lgtm, approved, cncf-cla: yes

#129 fix: improve release workflow with proper changelog and Docker image handling
  .github/workflows/release.yml
Labels: size/M, lgtm, approved, cncf-cla: yes
