Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-02, with the labels that each got.

#13 Make Inference-Perf Package-able / Use Modern Python Tooling
  .github/workflows/format.yml
  .pre-commit-config.yaml
  Makefile
  pdm.lock
  pyproject.toml
  requirements.txt
  requirements/build.txt
  requirements/run.txt
Labels: lgtm, approved, size/XL, cncf-cla: yes

#7 Added Abstract Type for Metrics Client
  inference_perf/client/metrics/README.md
  inference_perf/client/metrics/__init__.py
  inference_perf/client/metrics/client.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#20 Add Chen Wang to OWNERS
  OWNERS
Labels: lgtm, approved, size/XS, cncf-cla: yes
