Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-07, with the labels that each got.

#131 add config.md file to provide detail description for config.yml parameters
  CONFIG.md
  README.md
Labels: size/L, lgtm, approved, cncf-cla: yes

#130 Prometheus query fixes and examples update
  examples/vllm/config.yml
  examples/vllm/docker-compose.yml
  examples/vllm/prometheus.yml
  examples/vllm/vllm_server.ipynb
  inference_perf/client/metricsclient/prometheus_client/base.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/main.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#135 Add the ability to analyze reports and produce charts
  README.md
  docs/images/latency_vs_qps.png
  docs/images/throughput_vs_latency.png
  docs/images/throughput_vs_qps.png
  inference_perf/analysis/__init__.py
  inference_perf/analysis/analyze.py
  inference_perf/main.py
  pyproject.toml
Labels: size/L, lgtm, approved, cncf-cla: yes

#136 update datasets type
  README.md
Labels: approved, size/XS, cncf-cla: yes

#140 Fix a parsing issue with streaming requests
  inference_perf/apis/completion.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#147 feat: add support for s3 storage
  CONFIG.md
  inference_perf/client/filestorage/__init__.py
  inference_perf/client/filestorage/s3.py
  inference_perf/config.py
  inference_perf/main.py
  pdm.lock
  pyproject.toml
Labels: size/L, lgtm, approved, cncf-cla: yes

#145 Add detection for model_name and tokenizer
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
  inference_perf/main.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#149 update example config yml files
  examples/vllm/config-shared-prefix.yml
  examples/vllm/config-synthetic.yml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#143 Fix QPS accuracy at lower rates
  inference_perf/loadgen/load_generator.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#154 Update Helm chart
  deploy/inference-perf/README.md
  deploy/inference-perf/config.yaml
  deploy/inference-perf/templates/_helpers.tpl
  deploy/inference-perf/templates/configmap.yaml
  deploy/inference-perf/templates/job.yaml
  deploy/inference-perf/values.yaml
Labels: size/M, lgtm, approved, cncf-cla: yes

#155 Autocalc total_count
  examples/vllm/config-random.yml
  examples/vllm/config-synthetic.yml
  inference_perf/config.py
  inference_perf/datagen/random_datagen.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/main.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#160 fix: only assign tokenizer to model_name when not configured
  inference_perf/client/modelserver/vllm_client.py
Labels: lgtm, approved, size/XS, cncf-cla: yes
