Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-08, with the labels that each got.

#158 Point `config.yml` to mounted configmap file
  deploy/inference-perf/templates/job.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#168 update streaming part in the documentation too to make it clear
  CONFIG.md
Labels: lgtm, approved, size/XS, cncf-cla: yes

#172 Fix Malformed GMP Query URL
  inference_perf/client/metricsclient/prometheus_client/base.py
Labels: lgtm, approved, size/XS, cncf-cla: yes

#152 Support for running inference-perf offline
  CONFIG.md
  inference_perf/client/filestorage/s3.py
  inference_perf/config.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/main.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#175 Update manifests.yaml
  deploy/manifests.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#178 Change default api in config.yml from `chat` to `completion`
  config.yml
  tests/test_config.py
Labels: size/XS, cncf-cla: yes

#180 Remove outdated instructions in `deploy/README.md`
  deploy/README.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#173 Add Streaming Support for Chat API Requests
  CONFIG.md
  config.yml
  inference_perf/apis/chat.py
  inference_perf/client/modelserver/vllm_client.py
  tests/apis/test_chat.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#186 Fix for zeroed metrics added in #184
  inference_perf/client/metricsclient/base.py
Labels: lgtm, approved, size/XS, cncf-cla: yes

#177 Fix per stage PromQL metric queries by using `time.time()` instead of `time.perf_counter()`
  inference_perf/client/metricsclient/prometheus_client/base.py
  inference_perf/client/modelserver/mock_client.py
  inference_perf/loadgen/load_generator.py
  inference_perf/loadgen/load_timer.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#157 Defer InferenceAPIData gen to worker procs
  inference_perf/config.py
  inference_perf/datagen/random_datagen.py
  inference_perf/datagen/shared_prefix_datagen.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/loadgen/load_generator.py
  inference_perf/loadgen/load_timer.py
  pdm.lock
  pyproject.toml
Labels: size/L, lgtm, approved, cncf-cla: yes

#195 Rename schedule_accuracy to schedule_delay
  README.md
  inference_perf/reportgen/base.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#192 Support custom http headers in inference requests
  CONFIG.md
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/config.py
Labels: lgtm, approved, size/XS, cncf-cla: yes

#197 Add vllm metrics [preemptions and swapped requests] to prometheus metrics
  inference_perf/client/metricsclient/base.py
  inference_perf/client/modelserver/base.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/reportgen/base.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#200 Remove alpha channel of diagram png to keep presentation consistent in differen browser modes (#199)
  docs/images/architecture.png
Labels: lgtm, approved, size/XS, cncf-cla: yes

#196 Add cnn_dailymail datagen
  inference_perf/config.py
  inference_perf/datagen/__init__.py
  inference_perf/datagen/cnn_dailymail_datagen.py
  inference_perf/main.py
Labels: size/L, lgtm, approved, cncf-cla: yes
