Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-09, with the labels that each got.

#214 `iter -> itertools.cycle` in Datagen
  inference_perf/datagen/cnn_dailymail_datagen.py
  inference_perf/datagen/hf_sharegpt_datagen.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#216 Add vllm prefix metrics
  inference_perf/client/metricsclient/base.py
  inference_perf/client/modelserver/base.py
  inference_perf/client/modelserver/openai_client.py
  inference_perf/client/modelserver/sglang_client.py
  inference_perf/client/modelserver/vllm_client.py
  inference_perf/datagen/cnn_dailymail_datagen.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/reportgen/base.py
Labels: size/M, lgtm, approved, cncf-cla: yes

#219 Write config.yaml to report directory
  inference_perf/client/filestorage/local.py
  inference_perf/main.py
  inference_perf/reportgen/base.py
  inference_perf/utils/report_file.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#207 Update inf-perf to use hf-billsum dataset
  inference_perf/config.py
  inference_perf/datagen/__init__.py
  inference_perf/datagen/hf_billsum_datagen.py
  inference_perf/main.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#210 Improve efficiency and readability of data generators
  Dockerfile
  inference_perf/datagen/cnn_dailymail_datagen.py
  inference_perf/datagen/hf_billsum_datagen.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/datagen/infinity_instruct_datagen.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/datagen/random_datagen.py
  inference_perf/datagen/synthetic_datagen.py
  inference_perf/main.py
Labels: size/L, lgtm, approved, cncf-cla: yes
