Repository kubernetes-sigs/inference-perf, pull requests merged in 2025-03, with the labels that each got.

#27 Adding vLLM Client to inference perf runner
  .github/workflows/format.yml
  inference_perf/client/__init__.py
  inference_perf/client/base.py
  inference_perf/client/mock_client.py
  inference_perf/client/vllm_client.py
  inference_perf/loadgen/load_generator.py
  inference_perf/loadgen/load_timer.py
  inference_perf/main.py
  inference_perf/reportgen/__init__.py
  inference_perf/reportgen/base.py
  inference_perf/reportgen/mock_reportgen.py
Labels: size/L, lgtm, approved, cncf-cla: yes

#33 Add HF ShareGPT Data Generator
  inference_perf/datagen/__init__.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  pdm.lock
  pyproject.toml
Labels: size/L, lgtm, approved, cncf-cla: yes

#34 Parameterization of CLI tool using config file
  .github/workflows/format.yml
  Makefile
  README.md
  config.yml
  inference_perf/client/test_placeholder.py
  inference_perf/config.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/loadgen/__init__.py
  inference_perf/loadgen/load_generator.py
  inference_perf/main.py
  pdm.lock
  pyproject.toml
Labels: size/L, lgtm, approved, cncf-cla: yes

#36 Add SachinVarghese as approver, add owner aliases
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/S, approved, cncf-cla: yes

#38 Containerize the benchmark
  Dockerfile
  README.md
Labels: size/M, lgtm, approved, cncf-cla: yes

#44 Fix: Raising error for api type mismatch
  inference_perf/config.py
  inference_perf/datagen/base.py
  inference_perf/datagen/hf_sharegpt_datagen.py
  inference_perf/datagen/mock_datagen.py
  inference_perf/main.py
Labels: lgtm, size/S, approved, cncf-cla: yes
